/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GGegenstaendeRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord> implements org.jooq.Record2<java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 235286932;

	/**
	 * Setter for <code>schuldatenbank.g_gegenstaende.g_id</code>. 
	 */
	public void setGId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.g_gegenstaende.g_id</code>. 
	 */
	public java.lang.String getGId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.g_gegenstaende.g_bez</code>. 
	 */
	public void setGBez(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.g_gegenstaende.g_bez</code>. 
	 */
	public java.lang.String getGBez() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return at.halbarth.alexander.model.tables.GGegenstaende.G_GEGENSTAENDE.G_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.halbarth.alexander.model.tables.GGegenstaende.G_GEGENSTAENDE.G_BEZ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getGId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getGBez();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GGegenstaendeRecord
	 */
	public GGegenstaendeRecord() {
		super(at.halbarth.alexander.model.tables.GGegenstaende.G_GEGENSTAENDE);
	}

	/**
	 * Create a detached, initialised GGegenstaendeRecord
	 */
	public GGegenstaendeRecord(java.lang.String gId, java.lang.String gBez) {
		super(at.halbarth.alexander.model.tables.GGegenstaende.G_GEGENSTAENDE);

		setValue(0, gId);
		setValue(1, gBez);
	}
}
