/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LLehrerRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.LLehrerRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1604880543;

	/**
	 * Setter for <code>schuldatenbank.l_lehrer.l_id</code>. 
	 */
	public void setLId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.l_lehrer.l_id</code>. 
	 */
	public java.lang.String getLId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.l_lehrer.l_nachname</code>. 
	 */
	public void setLNachname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.l_lehrer.l_nachname</code>. 
	 */
	public java.lang.String getLNachname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>schuldatenbank.l_lehrer.l_vorname</code>. 
	 */
	public void setLVorname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>schuldatenbank.l_lehrer.l_vorname</code>. 
	 */
	public java.lang.String getLVorname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>schuldatenbank.l_lehrer.l_gebdat</code>. 
	 */
	public void setLGebdat(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>schuldatenbank.l_lehrer.l_gebdat</code>. 
	 */
	public java.sql.Date getLGebdat() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>schuldatenbank.l_lehrer.l_gehalt</code>. 
	 */
	public void setLGehalt(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>schuldatenbank.l_lehrer.l_gehalt</code>. 
	 */
	public java.lang.Integer getLGehalt() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>schuldatenbank.l_lehrer.l_v_vorgesetzte</code>. 
	 */
	public void setLVVorgesetzte(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>schuldatenbank.l_lehrer.l_v_vorgesetzte</code>. 
	 */
	public java.lang.String getLVVorgesetzte() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return at.halbarth.alexander.model.tables.LLehrer.L_LEHRER.L_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.halbarth.alexander.model.tables.LLehrer.L_LEHRER.L_NACHNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.halbarth.alexander.model.tables.LLehrer.L_LEHRER.L_VORNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return at.halbarth.alexander.model.tables.LLehrer.L_LEHRER.L_GEBDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return at.halbarth.alexander.model.tables.LLehrer.L_LEHRER.L_GEHALT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return at.halbarth.alexander.model.tables.LLehrer.L_LEHRER.L_V_VORGESETZTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getLId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLNachname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getLVorname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getLGebdat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getLGehalt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLVVorgesetzte();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached LLehrerRecord
	 */
	public LLehrerRecord() {
		super(at.halbarth.alexander.model.tables.LLehrer.L_LEHRER);
	}

	/**
	 * Create a detached, initialised LLehrerRecord
	 */
	public LLehrerRecord(java.lang.String lId, java.lang.String lNachname, java.lang.String lVorname, java.sql.Date lGebdat, java.lang.Integer lGehalt, java.lang.String lVVorgesetzte) {
		super(at.halbarth.alexander.model.tables.LLehrer.L_LEHRER);

		setValue(0, lId);
		setValue(1, lNachname);
		setValue(2, lVorname);
		setValue(3, lGebdat);
		setValue(4, lGehalt);
		setValue(5, lVVorgesetzte);
	}
}
