/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PPruefungenRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.PPruefungenRecord> implements org.jooq.Record6<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 959149025;

	/**
	 * Setter for <code>schuldatenbank.p_pruefungen.p_s_schueler</code>. 
	 */
	public void setPSSchueler(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.p_pruefungen.p_s_schueler</code>. 
	 */
	public java.lang.Integer getPSSchueler() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.p_pruefungen.p_datum</code>. 
	 */
	public void setPDatum(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.p_pruefungen.p_datum</code>. 
	 */
	public java.sql.Date getPDatum() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>schuldatenbank.p_pruefungen.p_l_lehrer</code>. 
	 */
	public void setPLLehrer(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>schuldatenbank.p_pruefungen.p_l_lehrer</code>. 
	 */
	public java.lang.String getPLLehrer() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>schuldatenbank.p_pruefungen.p_g_gegenstand</code>. 
	 */
	public void setPGGegenstand(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>schuldatenbank.p_pruefungen.p_g_gegenstand</code>. 
	 */
	public java.lang.String getPGGegenstand() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>schuldatenbank.p_pruefungen.p_field</code>. 
	 */
	public void setPField(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>schuldatenbank.p_pruefungen.p_field</code>. 
	 */
	public java.lang.String getPField() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>schuldatenbank.p_pruefungen.p_note</code>. 
	 */
	public void setPNote(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>schuldatenbank.p_pruefungen.p_note</code>. 
	 */
	public java.lang.Integer getPNote() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record4<java.lang.Integer, java.lang.String, java.sql.Date, java.lang.String> key() {
		return (org.jooq.Record4) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN.P_S_SCHUELER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN.P_DATUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN.P_L_LEHRER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN.P_G_GEGENSTAND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN.P_FIELD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN.P_NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getPSSchueler();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getPDatum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPLLehrer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPGGegenstand();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getPField();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getPNote();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PPruefungenRecord
	 */
	public PPruefungenRecord() {
		super(at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN);
	}

	/**
	 * Create a detached, initialised PPruefungenRecord
	 */
	public PPruefungenRecord(java.lang.Integer pSSchueler, java.sql.Date pDatum, java.lang.String pLLehrer, java.lang.String pGGegenstand, java.lang.String pField, java.lang.Integer pNote) {
		super(at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN);

		setValue(0, pSSchueler);
		setValue(1, pDatum);
		setValue(2, pLLehrer);
		setValue(3, pGGegenstand);
		setValue(4, pField);
		setValue(5, pNote);
	}
}
