/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RRaeumeRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.RRaeumeRecord> implements org.jooq.Record2<java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1297304489;

	/**
	 * Setter for <code>schuldatenbank.r_raeume.r_id</code>. 
	 */
	public void setRId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.r_raeume.r_id</code>. 
	 */
	public java.lang.String getRId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.r_raeume.r_anzahl</code>. 
	 */
	public void setRAnzahl(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.r_raeume.r_anzahl</code>. 
	 */
	public java.lang.Integer getRAnzahl() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return at.halbarth.alexander.model.tables.RRaeume.R_RAEUME.R_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return at.halbarth.alexander.model.tables.RRaeume.R_RAEUME.R_ANZAHL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getRId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRAnzahl();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RRaeumeRecord
	 */
	public RRaeumeRecord() {
		super(at.halbarth.alexander.model.tables.RRaeume.R_RAEUME);
	}

	/**
	 * Create a detached, initialised RRaeumeRecord
	 */
	public RRaeumeRecord(java.lang.String rId, java.lang.Integer rAnzahl) {
		super(at.halbarth.alexander.model.tables.RRaeume.R_RAEUME);

		setValue(0, rId);
		setValue(1, rAnzahl);
	}
}
