/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SSchuelerRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.SSchuelerRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -2076629770;

	/**
	 * Setter for <code>schuldatenbank.s_schueler.s_id</code>. 
	 */
	public void setSId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.s_schueler.s_id</code>. 
	 */
	public java.lang.Integer getSId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.s_schueler.s_nachname</code>. 
	 */
	public void setSNachname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.s_schueler.s_nachname</code>. 
	 */
	public java.lang.String getSNachname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>schuldatenbank.s_schueler.s_vorname</code>. 
	 */
	public void setSVorname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>schuldatenbank.s_schueler.s_vorname</code>. 
	 */
	public java.lang.String getSVorname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>schuldatenbank.s_schueler.s_gebdat</code>. 
	 */
	public void setSGebdat(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>schuldatenbank.s_schueler.s_gebdat</code>. 
	 */
	public java.sql.Date getSGebdat() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>schuldatenbank.s_schueler.s_ort</code>. 
	 */
	public void setSOrt(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>schuldatenbank.s_schueler.s_ort</code>. 
	 */
	public java.lang.String getSOrt() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>schuldatenbank.s_schueler.s_k_klasse</code>. 
	 */
	public void setSKKlasse(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>schuldatenbank.s_schueler.s_k_klasse</code>. 
	 */
	public java.lang.String getSKKlasse() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Date, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER.S_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER.S_NACHNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER.S_VORNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER.S_GEBDAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER.S_ORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER.S_K_KLASSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getSId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSNachname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSVorname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getSGebdat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSOrt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getSKKlasse();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SSchuelerRecord
	 */
	public SSchuelerRecord() {
		super(at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER);
	}

	/**
	 * Create a detached, initialised SSchuelerRecord
	 */
	public SSchuelerRecord(java.lang.Integer sId, java.lang.String sNachname, java.lang.String sVorname, java.sql.Date sGebdat, java.lang.String sOrt, java.lang.String sKKlasse) {
		super(at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER);

		setValue(0, sId);
		setValue(1, sNachname);
		setValue(2, sVorname);
		setValue(3, sGebdat);
		setValue(4, sOrt);
		setValue(5, sKKlasse);
	}
}
