/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StStundenRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.StStundenRecord> implements org.jooq.Record5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1897029487;

	/**
	 * Setter for <code>schuldatenbank.st_stunden.st_k_klasse</code>. 
	 */
	public void setStKKlasse(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.st_stunden.st_k_klasse</code>. 
	 */
	public java.lang.String getStKKlasse() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.st_stunden.st_l_lehrer</code>. 
	 */
	public void setStLLehrer(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.st_stunden.st_l_lehrer</code>. 
	 */
	public java.lang.String getStLLehrer() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>schuldatenbank.st_stunden.st_g_gegenstand</code>. 
	 */
	public void setStGGegenstand(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>schuldatenbank.st_stunden.st_g_gegenstand</code>. 
	 */
	public java.lang.String getStGGegenstand() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>schuldatenbank.st_stunden.st_zeit</code>. 
	 */
	public void setStZeit(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>schuldatenbank.st_stunden.st_zeit</code>. 
	 */
	public java.lang.String getStZeit() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>schuldatenbank.st_stunden.st_r_raum</code>. 
	 */
	public void setStRRaum(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>schuldatenbank.st_stunden.st_r_raum</code>. 
	 */
	public java.lang.String getStRRaum() {
		return (java.lang.String) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN.ST_K_KLASSE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN.ST_L_LEHRER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN.ST_G_GEGENSTAND;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN.ST_ZEIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN.ST_R_RAUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getStKKlasse();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStLLehrer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getStGGegenstand();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getStZeit();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getStRRaum();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached StStundenRecord
	 */
	public StStundenRecord() {
		super(at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN);
	}

	/**
	 * Create a detached, initialised StStundenRecord
	 */
	public StStundenRecord(java.lang.String stKKlasse, java.lang.String stLLehrer, java.lang.String stGGegenstand, java.lang.String stZeit, java.lang.String stRRaum) {
		super(at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN);

		setValue(0, stKKlasse);
		setValue(1, stLLehrer);
		setValue(2, stGGegenstand);
		setValue(3, stZeit);
		setValue(4, stRRaum);
	}
}
