/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VVorgesetzteRecord extends org.jooq.impl.UpdatableRecordImpl<at.halbarth.alexander.model.tables.records.VVorgesetzteRecord> implements org.jooq.Record3<java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -390534331;

	/**
	 * Setter for <code>schuldatenbank.v_vorgesetzte.v_id</code>. 
	 */
	public void setVId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>schuldatenbank.v_vorgesetzte.v_id</code>. 
	 */
	public java.lang.String getVId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>schuldatenbank.v_vorgesetzte.v_bez</code>. 
	 */
	public void setVBez(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>schuldatenbank.v_vorgesetzte.v_bez</code>. 
	 */
	public java.lang.String getVBez() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>schuldatenbank.v_vorgesetzte.v_l_chef</code>. 
	 */
	public void setVLChef(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>schuldatenbank.v_vorgesetzte.v_l_chef</code>. 
	 */
	public java.lang.String getVLChef() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.String, java.lang.String> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return at.halbarth.alexander.model.tables.VVorgesetzte.V_VORGESETZTE.V_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.halbarth.alexander.model.tables.VVorgesetzte.V_VORGESETZTE.V_BEZ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.halbarth.alexander.model.tables.VVorgesetzte.V_VORGESETZTE.V_L_CHEF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getVId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getVBez();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getVLChef();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VVorgesetzteRecord
	 */
	public VVorgesetzteRecord() {
		super(at.halbarth.alexander.model.tables.VVorgesetzte.V_VORGESETZTE);
	}

	/**
	 * Create a detached, initialised VVorgesetzteRecord
	 */
	public VVorgesetzteRecord(java.lang.String vId, java.lang.String vBez, java.lang.String vLChef) {
		super(at.halbarth.alexander.model.tables.VVorgesetzte.V_VORGESETZTE);

		setValue(0, vId);
		setValue(1, vBez);
		setValue(2, vLChef);
	}
}
