/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in schuldatenbank
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table schuldatenbank.g_gegenstaende
	 */
	public static final at.halbarth.alexander.model.tables.GGegenstaende G_GEGENSTAENDE = at.halbarth.alexander.model.tables.GGegenstaende.G_GEGENSTAENDE;

	/**
	 * The table schuldatenbank.k_klassen
	 */
	public static final at.halbarth.alexander.model.tables.KKlassen K_KLASSEN = at.halbarth.alexander.model.tables.KKlassen.K_KLASSEN;

	/**
	 * The table schuldatenbank.l_lehrer
	 */
	public static final at.halbarth.alexander.model.tables.LLehrer L_LEHRER = at.halbarth.alexander.model.tables.LLehrer.L_LEHRER;

	/**
	 * The table schuldatenbank.p_pruefungen
	 */
	public static final at.halbarth.alexander.model.tables.PPruefungen P_PRUEFUNGEN = at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN;

	/**
	 * The table schuldatenbank.r_raeume
	 */
	public static final at.halbarth.alexander.model.tables.RRaeume R_RAEUME = at.halbarth.alexander.model.tables.RRaeume.R_RAEUME;

	/**
	 * The table schuldatenbank.st_stunden
	 */
	public static final at.halbarth.alexander.model.tables.StStunden ST_STUNDEN = at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN;

	/**
	 * The table schuldatenbank.s_schueler
	 */
	public static final at.halbarth.alexander.model.tables.SSchueler S_SCHUELER = at.halbarth.alexander.model.tables.SSchueler.S_SCHUELER;

	/**
	 * The table schuldatenbank.v_vorgesetzte
	 */
	public static final at.halbarth.alexander.model.tables.VVorgesetzte V_VORGESETZTE = at.halbarth.alexander.model.tables.VVorgesetzte.V_VORGESETZTE;
}
