/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GGegenstaende extends org.jooq.impl.TableImpl<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord> {

	private static final long serialVersionUID = 876427267;

	/**
	 * The singleton instance of <code>schuldatenbank.g_gegenstaende</code>
	 */
	public static final at.halbarth.alexander.model.tables.GGegenstaende G_GEGENSTAENDE = new at.halbarth.alexander.model.tables.GGegenstaende();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord> getRecordType() {
		return at.halbarth.alexander.model.tables.records.GGegenstaendeRecord.class;
	}

	/**
	 * The column <code>schuldatenbank.g_gegenstaende.g_id</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord, java.lang.String> G_ID = createField("g_id", org.jooq.impl.SQLDataType.CHAR.length(4).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.g_gegenstaende.g_bez</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord, java.lang.String> G_BEZ = createField("g_bez", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this);

	/**
	 * Create a <code>schuldatenbank.g_gegenstaende</code> table reference
	 */
	public GGegenstaende() {
		super("g_gegenstaende", at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK);
	}

	/**
	 * Create an aliased <code>schuldatenbank.g_gegenstaende</code> table reference
	 */
	public GGegenstaende(java.lang.String alias) {
		super(alias, at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK, at.halbarth.alexander.model.tables.GGegenstaende.G_GEGENSTAENDE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord> getPrimaryKey() {
		return at.halbarth.alexander.model.Keys.KEY_G_GEGENSTAENDE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.GGegenstaendeRecord>>asList(at.halbarth.alexander.model.Keys.KEY_G_GEGENSTAENDE_PRIMARY, at.halbarth.alexander.model.Keys.KEY_G_GEGENSTAENDE_G_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.halbarth.alexander.model.tables.GGegenstaende as(java.lang.String alias) {
		return new at.halbarth.alexander.model.tables.GGegenstaende(alias);
	}
}
