/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KKlassen extends org.jooq.impl.TableImpl<at.halbarth.alexander.model.tables.records.KKlassenRecord> {

	private static final long serialVersionUID = -1806420431;

	/**
	 * The singleton instance of <code>schuldatenbank.k_klassen</code>
	 */
	public static final at.halbarth.alexander.model.tables.KKlassen K_KLASSEN = new at.halbarth.alexander.model.tables.KKlassen();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.halbarth.alexander.model.tables.records.KKlassenRecord> getRecordType() {
		return at.halbarth.alexander.model.tables.records.KKlassenRecord.class;
	}

	/**
	 * The column <code>schuldatenbank.k_klassen.k_id</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.KKlassenRecord, java.lang.String> K_ID = createField("k_id", org.jooq.impl.SQLDataType.CHAR.length(4).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.k_klassen.k_bez</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.KKlassenRecord, java.lang.String> K_BEZ = createField("k_bez", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.k_klassen.k_s_klassensprecher</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.KKlassenRecord, java.lang.Integer> K_S_KLASSENSPRECHER = createField("k_s_klassensprecher", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>schuldatenbank.k_klassen.k_s_klassensprecherstv</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.KKlassenRecord, java.lang.Integer> K_S_KLASSENSPRECHERSTV = createField("k_s_klassensprecherstv", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>schuldatenbank.k_klassen.k_l_kvorstand</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.KKlassenRecord, java.lang.String> K_L_KVORSTAND = createField("k_l_kvorstand", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false), this);

	/**
	 * Create a <code>schuldatenbank.k_klassen</code> table reference
	 */
	public KKlassen() {
		super("k_klassen", at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK);
	}

	/**
	 * Create an aliased <code>schuldatenbank.k_klassen</code> table reference
	 */
	public KKlassen(java.lang.String alias) {
		super(alias, at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK, at.halbarth.alexander.model.tables.KKlassen.K_KLASSEN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.KKlassenRecord> getPrimaryKey() {
		return at.halbarth.alexander.model.Keys.KEY_K_KLASSEN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.KKlassenRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.KKlassenRecord>>asList(at.halbarth.alexander.model.Keys.KEY_K_KLASSEN_PRIMARY, at.halbarth.alexander.model.Keys.KEY_K_KLASSEN_K_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.halbarth.alexander.model.tables.KKlassen as(java.lang.String alias) {
		return new at.halbarth.alexander.model.tables.KKlassen(alias);
	}
}
