/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PPruefungen extends org.jooq.impl.TableImpl<at.halbarth.alexander.model.tables.records.PPruefungenRecord> {

	private static final long serialVersionUID = -1245912984;

	/**
	 * The singleton instance of <code>schuldatenbank.p_pruefungen</code>
	 */
	public static final at.halbarth.alexander.model.tables.PPruefungen P_PRUEFUNGEN = new at.halbarth.alexander.model.tables.PPruefungen();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.halbarth.alexander.model.tables.records.PPruefungenRecord> getRecordType() {
		return at.halbarth.alexander.model.tables.records.PPruefungenRecord.class;
	}

	/**
	 * The column <code>schuldatenbank.p_pruefungen.p_s_schueler</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.PPruefungenRecord, java.lang.Integer> P_S_SCHUELER = createField("p_s_schueler", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>schuldatenbank.p_pruefungen.p_datum</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.PPruefungenRecord, java.sql.Date> P_DATUM = createField("p_datum", org.jooq.impl.SQLDataType.DATE.nullable(false), this);

	/**
	 * The column <code>schuldatenbank.p_pruefungen.p_l_lehrer</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.PPruefungenRecord, java.lang.String> P_L_LEHRER = createField("p_l_lehrer", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.p_pruefungen.p_g_gegenstand</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.PPruefungenRecord, java.lang.String> P_G_GEGENSTAND = createField("p_g_gegenstand", org.jooq.impl.SQLDataType.CHAR.length(4).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.p_pruefungen.p_field</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.PPruefungenRecord, java.lang.String> P_FIELD = createField("p_field", org.jooq.impl.SQLDataType.VARCHAR.length(3).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.p_pruefungen.p_note</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.PPruefungenRecord, java.lang.Integer> P_NOTE = createField("p_note", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>schuldatenbank.p_pruefungen</code> table reference
	 */
	public PPruefungen() {
		super("p_pruefungen", at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK);
	}

	/**
	 * Create an aliased <code>schuldatenbank.p_pruefungen</code> table reference
	 */
	public PPruefungen(java.lang.String alias) {
		super(alias, at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK, at.halbarth.alexander.model.tables.PPruefungen.P_PRUEFUNGEN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.PPruefungenRecord> getPrimaryKey() {
		return at.halbarth.alexander.model.Keys.KEY_P_PRUEFUNGEN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.PPruefungenRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.PPruefungenRecord>>asList(at.halbarth.alexander.model.Keys.KEY_P_PRUEFUNGEN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.halbarth.alexander.model.tables.PPruefungen as(java.lang.String alias) {
		return new at.halbarth.alexander.model.tables.PPruefungen(alias);
	}
}
