/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RRaeume extends org.jooq.impl.TableImpl<at.halbarth.alexander.model.tables.records.RRaeumeRecord> {

	private static final long serialVersionUID = -1350157372;

	/**
	 * The singleton instance of <code>schuldatenbank.r_raeume</code>
	 */
	public static final at.halbarth.alexander.model.tables.RRaeume R_RAEUME = new at.halbarth.alexander.model.tables.RRaeume();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.halbarth.alexander.model.tables.records.RRaeumeRecord> getRecordType() {
		return at.halbarth.alexander.model.tables.records.RRaeumeRecord.class;
	}

	/**
	 * The column <code>schuldatenbank.r_raeume.r_id</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.RRaeumeRecord, java.lang.String> R_ID = createField("r_id", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.r_raeume.r_anzahl</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.RRaeumeRecord, java.lang.Integer> R_ANZAHL = createField("r_anzahl", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>schuldatenbank.r_raeume</code> table reference
	 */
	public RRaeume() {
		super("r_raeume", at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK);
	}

	/**
	 * Create an aliased <code>schuldatenbank.r_raeume</code> table reference
	 */
	public RRaeume(java.lang.String alias) {
		super(alias, at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK, at.halbarth.alexander.model.tables.RRaeume.R_RAEUME);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.RRaeumeRecord> getPrimaryKey() {
		return at.halbarth.alexander.model.Keys.KEY_R_RAEUME_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.RRaeumeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.RRaeumeRecord>>asList(at.halbarth.alexander.model.Keys.KEY_R_RAEUME_PRIMARY, at.halbarth.alexander.model.Keys.KEY_R_RAEUME_R_ID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.halbarth.alexander.model.tables.RRaeume as(java.lang.String alias) {
		return new at.halbarth.alexander.model.tables.RRaeume(alias);
	}
}
