/**
 * This class is generated by jOOQ
 */
package at.halbarth.alexander.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StStunden extends org.jooq.impl.TableImpl<at.halbarth.alexander.model.tables.records.StStundenRecord> {

	private static final long serialVersionUID = -2034483397;

	/**
	 * The singleton instance of <code>schuldatenbank.st_stunden</code>
	 */
	public static final at.halbarth.alexander.model.tables.StStunden ST_STUNDEN = new at.halbarth.alexander.model.tables.StStunden();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.halbarth.alexander.model.tables.records.StStundenRecord> getRecordType() {
		return at.halbarth.alexander.model.tables.records.StStundenRecord.class;
	}

	/**
	 * The column <code>schuldatenbank.st_stunden.st_k_klasse</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.StStundenRecord, java.lang.String> ST_K_KLASSE = createField("st_k_klasse", org.jooq.impl.SQLDataType.CHAR.length(4).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.st_stunden.st_l_lehrer</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.StStundenRecord, java.lang.String> ST_L_LEHRER = createField("st_l_lehrer", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.st_stunden.st_g_gegenstand</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.StStundenRecord, java.lang.String> ST_G_GEGENSTAND = createField("st_g_gegenstand", org.jooq.impl.SQLDataType.CHAR.length(4).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.st_stunden.st_zeit</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.StStundenRecord, java.lang.String> ST_ZEIT = createField("st_zeit", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this);

	/**
	 * The column <code>schuldatenbank.st_stunden.st_r_raum</code>. 
	 */
	public final org.jooq.TableField<at.halbarth.alexander.model.tables.records.StStundenRecord, java.lang.String> ST_R_RAUM = createField("st_r_raum", org.jooq.impl.SQLDataType.CHAR.length(3).nullable(false), this);

	/**
	 * Create a <code>schuldatenbank.st_stunden</code> table reference
	 */
	public StStunden() {
		super("st_stunden", at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK);
	}

	/**
	 * Create an aliased <code>schuldatenbank.st_stunden</code> table reference
	 */
	public StStunden(java.lang.String alias) {
		super(alias, at.halbarth.alexander.model.Schuldatenbank.SCHULDATENBANK, at.halbarth.alexander.model.tables.StStunden.ST_STUNDEN);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.StStundenRecord> getPrimaryKey() {
		return at.halbarth.alexander.model.Keys.KEY_ST_STUNDEN_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.StStundenRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.halbarth.alexander.model.tables.records.StStundenRecord>>asList(at.halbarth.alexander.model.Keys.KEY_ST_STUNDEN_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.halbarth.alexander.model.tables.StStunden as(java.lang.String alias) {
		return new at.halbarth.alexander.model.tables.StStunden(alias);
	}
}
